name       : iwd
version    : 1.29
release    : 2
source     :
    - https://mirrors.edge.kernel.org/pub/linux/network/wireless/iwd-1.29.tar.xz : 71533fe3b8f6381f24832198ba11d00f04a361454770c173b3b66bc3cdf272bd
homepage   : https://iwd.wiki.kernel.org
license    : LGPL-2.1-or-later
component  : network.base
summary    : iNet Wireless Daemon (replacement for wpa_supplicant)
description: |
    iNet Wireless Daemon (iwd) project aims to provide a comprehensive Wi-Fi connectivity solution for Linux based devices. The core goal of the project is to optimize resource utilization: storage, runtime memory and link-time costs. This is accomplished by not depending on any external libraries and utilizes features provided by the Linux Kernel to the maximum extent possible. The result is a self-contained environment that only depends on the Linux Kernel and the runtime C library.
setup      : |
    %configure \
        --enable-wired \
        --enable-ofono \
        --enable-hwsim \
        --disable-tools
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
